[package]
name = "bevy_example"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { git = "https://github.com/bevyengine/bevy.git", rev = "d06aa47" }
bevy_egui = { git = "https://github.com/taboky-dev/bevy_egui", branch = "bevy-0.19" }
ratatui = { workspace = true }
egui_ratatui = { workspace = true }
soft_ratatui = { workspace = true, features = ["unicodefonts"] }


